server:
  port: 9090

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: User
              uri: lb://User
              predicates:
                - Path=/users/**
            - id: Product
              uri: lb://Product
              predicates:
                - Path=/products/**
            - id: Order
              uri: lb://Order
              predicates:
                - Path=/orders/**
                
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
